const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const ohlcSchema = new Schema({index: { type: Date, required: true },
xle_close: { type: Number, required: true },
xlu_close: { type: Number, required: true },
xly_close: { type: Number, required: true },
xlp_close: { type: Number, required: true },
xlb_close: { type: Number, required: true },
xlf_close: { type: Number, required: true },
xlk_close: { type: Number, required: true },
xli_close: { type: Number, required: true },
xlv_close: { type: Number, required: true },
tlt_close: { type: Number, required: true },
spy_close: { type: Number, required: true },
spxtr: { type: Number, required: true },
spxtr_roc: { type: Number, required: true },
xle_closeroc5: { type: Number, required: true },
xlu_closeroc5: { type: Number, required: true },
xly_closeroc5: { type: Number, required: true },
xlp_closeroc5: { type: Number, required: true },
xlb_closeroc5: { type: Number, required: true },
xlf_closeroc5: { type: Number, required: true },
xlk_closeroc5: { type: Number, required: true },
xli_closeroc5: { type: Number, required: true },
xlv_closeroc5: { type: Number, required: true },
tlt_closeroc5: { type: Number, required: true },
spy_closeroc5: { type: Number, required: true },
spxtrroc5: { type: Number, required: true },
spxtr_rocroc5: { type: Number, required: true },
xle_closeroc8: { type: Number, required: true },
xlu_closeroc8: { type: Number, required: true },
xly_closeroc8: { type: Number, required: true },
xlp_closeroc8: { type: Number, required: true },
xlb_closeroc8: { type: Number, required: true },
xlf_closeroc8: { type: Number, required: true },
xlk_closeroc8: { type: Number, required: true },
xli_closeroc8: { type: Number, required: true },
xlv_closeroc8: { type: Number, required: true },
tlt_closeroc8: { type: Number, required: true },
spy_closeroc8: { type: Number, required: true },
spxtrroc8: { type: Number, required: true },
spxtr_rocroc8: { type: Number, required: true },
xle_closeroc21: { type: Number, required: true },
xlu_closeroc21: { type: Number, required: true },
xly_closeroc21: { type: Number, required: true },
xlp_closeroc21: { type: Number, required: true },
xlb_closeroc21: { type: Number, required: true },
xlf_closeroc21: { type: Number, required: true },
xlk_closeroc21: { type: Number, required: true },
xli_closeroc21: { type: Number, required: true },
xlv_closeroc21: { type: Number, required: true },
tlt_closeroc21: { type: Number, required: true },
spy_closeroc21: { type: Number, required: true },
spxtrroc21: { type: Number, required: true },
spxtr_rocroc21: { type: Number, required: true },
xle_closeroc55: { type: Number, required: true },
xlu_closeroc55: { type: Number, required: true },
xly_closeroc55: { type: Number, required: true },
xlp_closeroc55: { type: Number, required: true },
xlb_closeroc55: { type: Number, required: true },
xlf_closeroc55: { type: Number, required: true },
xlk_closeroc55: { type: Number, required: true },
xli_closeroc55: { type: Number, required: true },
xlv_closeroc55: { type: Number, required: true },
tlt_closeroc55: { type: Number, required: true },
spy_closeroc55: { type: Number, required: true },
spxtrroc55: { type: Number, required: true },
spxtr_rocroc55: { type: Number, required: true }
}, {
  timestamps: true,
  collection: 'ohlc'
});

const ohlc = mongoose.model('ohlc', ohlcSchema);

module.exports = ohlc;